chore: update to go 1.21.5 in docker
kubernetes-sigs/secrets-store-csi-driver pull request #1393
Opened 2023-12-15 19:10 UTC by dargudear-google

/kind feature

update to go 1.21.5 for docker builds

2024-01-08 16:56 UTC, nilekhc commented
/ok-to-test

2024-01-08 18:07 UTC, dargudear-google commented
/retest

2024-01-08 18:17 UTC, dargudear-google commented
/retest-required

2024-01-09 05:28 UTC, dargudear-google commented
/retest-required

2024-01-09 21:35 UTC, aramase requested changes
Thank you for the PR! Added comments, PTAL!

After the comments are solved, please rebase and squash to a single commit.

2024-01-09 21:35 UTC, aramase commented on docker/Dockerfile
> +FROM golang:1.21@sha256:2ff79bcdaff74368a9fdcb06f6599e54a71caf520fd2357a55feddd504bcaffb as builder
The sha for latest `1.21.5` image is [`135ba6c2ae2a9a022f53f3eee24ef213bc62e876811cd9582b91045168206873`]( https://hub.docker.com/layers/library/golang/1.21/images/sha256-135ba6c2ae2a9a022f53f3eee24ef213bc62e876811cd9582b91045168206873?context=explore)

2024-01-09 21:35 UTC, aramase commented on docker/windows.Dockerfile
> +FROM --platform=$BUILDPLATFORM golang:1.21@sha256:2ff79bcdaff74368a9fdcb06f6599e54a71caf520fd2357a55feddd504bcaffb as builder
same comment as above

2024-01-09 21:35 UTC, aramase commented on test/e2eprovider/Dockerfile
> +FROM golang:1.21@sha256:2ff79bcdaff74368a9fdcb06f6599e54a71caf520fd2357a55feddd504bcaffb as builder
same comment as above

2024-01-09 21:35 UTC, aramase commented on .local/Dockerfile
> +FROM golang:1.21-alpine@sha256:55f716237933c85cee01748700755b4ac8736fb1ca974c9aed051691b68d6dc2
The sha for latest `1.21.5` image is [`101168f254556b660b19fd7c542cde4cdc963053573e67825ed16b8fe20e1ff8`](https://hub.docker.com/layers/library/golang/1.21-alpine/images/sha256-101168f254556b660b19fd7c542cde4cdc963053573e67825ed16b8fe20e1ff8?context=explore)

2024-01-09 23:33 UTC, aramase reviewed
`1.21.6` base images are already available, so I would suggest bumping to that instead of `1.21.5`

2024-01-10 10:41 UTC, dargudear-google commented
> `1.21.6` base images are already available, so I would suggest bumping to that instead of `1.21.5`

Done. PTAL.

2024-01-10 17:13 UTC, aramase reviewed
/lgtm
/approve

2024-01-10 18:25 UTC, merged