TEST: GCP e2e test
kubernetes-sigs/secrets-store-csi-driver pull request #1701
Opened 2024-12-05 13:04 UTC by dargudear-google

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

2024-12-05 13:44 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 14:46 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 14:59 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 15:03 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 15:18 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 16:05 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 16:41 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 17:15 UTC, dargudear-google commented
test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 17:16 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 17:33 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 17:36 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 17:55 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 18:15 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-06 19:00 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-07 09:34 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 16:47 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 17:21 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 17:24 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 17:25 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 17:36 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 18:43 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 19:17 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 19:39 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 19:42 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-08 20:02 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-09 04:42 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-09 04:45 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-13 18:32 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2024-12-13 18:36 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-07 11:16 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-07 15:49 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-08 04:48 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-08 14:56 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-08 15:51 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-09 02:37 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-09 02:50 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-09 08:14 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-09 08:20 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-09 13:40 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-09 16:14 UTC, aramase commented
/test: add e2e test setup for GCP provider

2025-01-09 18:00 UTC, aramase requested changes
Few minor nits!

2025-01-09 18:00 UTC, aramase commented on test/scripts/run-e2e-gcp.sh
> +    #install boskosctl
```suggestion
    # install boskosctl
```

2025-01-09 18:00 UTC, aramase commented on test/scripts/run-e2e-gcp.sh
> +    # Aquire a project from boskos pool, test will use secret created on this aquired project
```suggestion
    # Acquire a project from boskos pool, test will use secret created on this acquired project
```

2025-01-10 01:26 UTC, dargudear-google commented on test/bats/gcp.bats
> +  sleep 120
This is not for secret manager but for driver.

2025-01-10 01:45 UTC, aramase reviewed
Please squash to a single commit after resolving https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1701#discussion_r1909660900

2025-01-10 02:11 UTC, dargudear-google commented
/test pull-secrets-store-csi-driver-e2e-gcp

2025-01-10 02:19 UTC, dargudear-google commented
> Please squash to a single commit after resolving [#1701 (comment)](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1701#discussion_r1909660900)

Done.

2025-01-10 02:35 UTC, aramase reviewed
/lgtm
/approve

2025-01-10 02:36 UTC, aramase commented
/retest-required

2025-01-10 03:06 UTC, merged

2025-01-27 22:54 UTC, aramase commented
/cherrypick release-1.4