Switch to using official images for containers
kubernetes-sigs/secrets-store-csi-driver pull request #358
Opened 2020-10-22 14:54 UTC by Evalle

**What this PR does / why we need it**:
The `node-driver-registrar` and `liveness-probe` container images are currently referenced from mcr for Windows and quay registry for Linux.

`k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1` and `k8s.gcr.io/sig-storage/livenessprobe:v2.1.0` container images now support multi-arch. This PR switches the images in the manifest_staging dir to use the official images for linux and windows.

**Which issue(s) this PR fixes** 
Fixes #357

**Special notes for your reviewer**:
I can create two new values for general images for mcft and linux in `values.yaml` but I don't know your opinion on that. 
Thank you

2020-10-22 14:55 UTC, Evalle commented
/assign  @aramase

2020-10-22 16:11 UTC, aramase requested changes

2020-10-22 16:11 UTC, aramase commented on manifest_staging/charts/secrets-store-csi-driver/README.md
> +| `linux.livenessProbeImage.tag`          | Linux liveness-probe image tag                                                                                                    | `v2.0.1`
liveness probe image tag is `v2.1.0`

2020-10-22 16:11 UTC, aramase commented on manifest_staging/charts/secrets-store-csi-driver/README.md
> +| `windows.livenessProbeImage.tag`        | Windows liveness-probe image tag                                                                                                  | `v2.0.1`
liveness probe image tag is `v2.1.0`

2020-10-22 16:11 UTC, aramase commented on manifest_staging/charts/secrets-store-csi-driver/values.yaml
> +    tag: v2.0.1
ditto (https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.1.0)

2020-10-22 16:11 UTC, aramase commented on manifest_staging/charts/secrets-store-csi-driver/values.yaml
> +    tag: v2.0.1
ditto (https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.1.0)

2020-10-23 13:10 UTC, Evalle commented
Done, @aramase

2020-10-23 16:34 UTC, aramase commented
/ok-to-test

2020-10-23 19:05 UTC, aramase commented
/retest

2020-10-23 19:14 UTC, aramase commented
/test pull-secrets-store-csi-driver-e2e-windows

2020-10-23 20:16 UTC, aramase reviewed
/lgtm

2020-10-23 20:34 UTC, ritazh commented
/approve

2020-10-23 20:39 UTC, merged