Update otel to 0.13.0
kubernetes-sigs/secrets-store-csi-driver pull request #374
Opened 2020-11-09 01:58 UTC by vladdy

**What this PR does / why we need it**:
This updates the dependency to the latest release: 0.13.0

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #324

**Special notes for your reviewer**:
Since Prometheus exporter now uses a much simpler `pull.Controller` which does not have the `Stop()` method, I took a shortcut and just removed its call from `cmd/secrets-store-csi-driver/main.go`. Let me know if it would still be preferable to wrap the Prometheus' HTTP handler into `http.server` and export its `Shutdown()` method in a generic `Stop()`.

2020-11-09 18:30 UTC, aramase commented
/ok-to-test

2020-11-09 20:30 UTC, aramase requested changes
@vladdy Thank you for the PR. Added few comments.

The duration needs to be of type `Float64ValueRecorder` so it can record the duration and add to the histogram bucket.

2020-11-09 20:30 UTC, aramase commented on pkg/rotation/stats_reporter.go
> +	rotationReconcileDuration   metric.Float64Counter
This should be `Float64ValueRecorder` as it records duration

2020-11-09 20:30 UTC, aramase commented on pkg/rotation/stats_reporter.go
> +	rotationReconcileDuration = metric.Must(meter).NewFloat64Counter("rotation_reconcile_duration_sec", metric.WithDescription("Distribution of how long it took to rotate secrets-store content for pods"
```suggestion
	rotationReconcileDuration = metric.Must(meter).NewFloat64ValueRecorder("rotation_reconcile_duration_sec", metric.WithDescription("Distribution of how long it took to rotate secrets-store content for pods"))
```

2020-11-09 20:30 UTC, aramase commented on pkg/secrets-store/stats_reporter.go
> +	syncK8sSecretDuration = metric.Must(meter).NewFloat64Counter("sync_k8s_secret_duration_sec", metric.WithDescription("Distribution of how long it took to sync k8s secret"))
```suggestion
	syncK8sSecretDuration = metric.Must(meter).NewFloat64ValueRecorder("sync_k8s_secret_duration_sec", metric.WithDescription("Distribution of how long it took to sync k8s secret"))
```

2020-11-09 20:30 UTC, aramase commented on pkg/secrets-store/stats_reporter.go
> +	syncK8sSecretDuration   metric.Float64Counter
```suggestion
	syncK8sSecretDuration   metric.Float64ValueRecorder
```

2020-11-09 20:30 UTC, aramase commented on pkg/rotation/stats_reporter.go
> +	rotationReconcileDuration   metric.Float64Counter
```suggestion
	rotationReconcileDuration   metric.Float64ValueRecorder
```

2020-11-09 22:13 UTC, vladdy commented
@aramase, True, I missed that part. Thanks for catching!

2020-11-09 23:10 UTC, aramase reviewed
@vladdy Thank you for the PR  🎉 

/lgtm

2020-11-09 23:10 UTC, aramase commented
/cc @tam7t

2020-11-09 23:48 UTC, aramase commented
/retitle chore: update otel to v0.13.0

2020-11-10 00:46 UTC, ritazh commented
/approve

2020-11-10 00:48 UTC, merged