Update command reference docs book
kubernetes-sigs/secrets-store-csi-driver pull request #903
Opened 2022-03-16 19:33 UTC by umeshkumhar

**What this PR does / why we need it**: This is raised to add a new subpage under topics around command reference

**Which issue(s) this PR fixes**:
Fixes #855 

**Special notes for your reviewer**: 
- Do let me know if **Command Reference** title works else we can update with **Command Line Arguments** or **Configuration Options**

2022-03-16 21:12 UTC, aramase commented
/cc @tam7t 
/retitle docs: add command reference
/ok-to-test

2022-03-17 12:34 UTC, nilekhc commented on docs/book/src/topics/command-reference.md
> +| `--rotation-poll-interval`           | Secret rotation poll interval duration                                 |                                             |
default rotation poll interval is `2m`

2022-03-17 21:34 UTC, aramase reviewed
Thanks for the PR @umeshkumhar! 

overall lgtm, added one minor comment. Could you also [squash](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits) to single commit?

2022-03-17 21:34 UTC, aramase commented on docs/book/src/topics/command-reference.md
> +The Secrets Store CSI Driver can be provided with the following command line arguments.
```suggestion
The `secrets-store` container in the DaemonSet can be configured using the following command line arguments:
```

2022-03-18 09:23 UTC, nilekhc commented
> Thanks for the PR @umeshkumhar!
> 
> overall lgtm, added one minor comment. Could you also [squash](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits) to single commit?

/hold

2022-03-18 09:25 UTC, nilekhc commented
/lgtm

2022-03-18 09:26 UTC, nilekhc commented
/unhold

2022-03-18 16:21 UTC, aramase requested changes
The changes in `Makefile`, `docker/Dockerfile` and `docker/Makefile` are already in the main branch. Looks like this PR needs to be rebased so those changes aren't being added again as part of the PR. Could you rebase the PR on top of the main branch?

2022-03-22 18:14 UTC, merged